version: '3.2'

services:
  ipld-eth-db:
    restart: always
    image: vulcanize/ipld-eth-db
    build: .
    environment:
      POSTGRES_USER: "vdbm"
      POSTGRES_DB: "vulcanize_public"
      POSTGRES_PASSWORD: "password"
      hostname: db
    ports:
      - "127.0.0.1:8077:5432"